name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: shakhriyor-dev
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake to repository
        uses: EndBug/add-and-commit@v9
        with:
          add: dist/github-contribution-grid-snake.svg
          message: "Generate contribution snake"
